* [Indexing](#Indexing)

In [1]:
import numpy as np

In [2]:
a = np.arange(12)
b = a
b is a

True

In [4]:
b.shape = 3,4
b.shape

(3, 4)

In [8]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
a.reshape(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
b

array([[ 0,  1,  2,  3, 10],
       [11, 12, 13, 20, 21],
       [22, 23, 30, 31, 32],
       [33, 40, 41, 42, 43]])

In [14]:
def f(x,y):
...     return 10*x+y
b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [15]:
b = np.fromfunction(lambda x,y:10*x+y,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [16]:
b[2]

array([20, 21, 22, 23])

In [17]:
b.ravel()

array([ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21, 22, 23, 30, 31, 32, 33, 40,
       41, 42, 43])

In [18]:
b.T

array([[ 0, 10, 20, 30, 40],
       [ 1, 11, 21, 31, 41],
       [ 2, 12, 22, 32, 42],
       [ 3, 13, 23, 33, 43]])

In [22]:
b.resize(4,5)
b

array([[ 0,  1,  2,  3, 10],
       [11, 12, 13, 20, 21],
       [22, 23, 30, 31, 32],
       [33, 40, 41, 42, 43]])

In [23]:
b.reshape(2,-1)

array([[ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21],
       [22, 23, 30, 31, 32, 33, 40, 41, 42, 43]])

In [24]:
b

array([[ 0,  1,  2,  3, 10],
       [11, 12, 13, 20, 21],
       [22, 23, 30, 31, 32],
       [33, 40, 41, 42, 43]])

In [33]:
list1 = [3,5,-4,-1,0,-2,-6]
sorted(list1, key=lambda x: abs(x))

[0, -1, -2, 3, -4, 5, -6]

# Indexing

In [34]:
list1.resize()

AttributeError: 'list' object has no attribute 'resize'